#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""pred_CBED.ipynb

Automatically generated by Colaboratory.
Referred to Pytorch ZetoToAll
Original file is located at
    https://colab.research.google.com/drive/1so8i-5nk4xpYEuXOXbHDgkIfe8b1LLav
"""
import sys
import numpy as np
from matplotlib import pyplot as plt
import h5py

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

f = h5py.File(sys.argv[1], mode='r', swmr=True)
keys = list(f.keys())
_len = len(keys)
tmp_x, tmp_y = [], []
for i in range(1):
    tmp_x.append(dict(f[keys[i]].items())['cbed_stack'][()])
    #tmp_y.append(dict(f[keys[i]].items())['cbed_stack'][()][1])
    #tmp_z.append(dict(f[keys[i]].items())['cbed_stack'][()][2])
    tmp_y.append(int(dict(f[keys[i]].attrs.items())['space_group']))

print(tmp_x, tmp_y)
